[data]
n_samples = 20000
random_seed = 42
age_min = 25
age_max = 65
balance_min = 20000
balance_max = 300000
num_accounts_min = 1
num_accounts_max = 4
last_login_days_min = 1
last_login_days_max = 180
satisfaction_score_min = 1
satisfaction_score_max = 5

[email]
domains = [
    "gmail.com",
    "yahoo.com.au",
    "outlook.com",
    "bigpond.com",
    "hotmail.com",
    "optusnet.com.au",
    "icloud.com"
]
